"use strict";
exports.__esModule = true;
var persona_1 = require("../Ts/persona");
var direccion_1 = require("../Ts/direccion");
var mail_1 = require("../Ts/mail");
var telefono_1 = require("../Ts/telefono");
var primeraResidenciaRocio = new direccion_1.Direccion("Calle Victoria", 31, 3, "B", 29012, "Malaga", "Malaga");
var segundaResidenciaRocio = new direccion_1.Direccion("Calle Benahavis", 1, false, false, 29004, "Malaga", "Malaga");
var mailRocio = new mail_1.Mail("personal", "fernandezrocio@gmail.com");
var telefonoFijoRocio = new telefono_1.Telefono("fijo", 952345673);
var telefonoMovilRocio = new telefono_1.Telefono("movil", 678546782);
var datosRocio = new persona_1.Persona('Rocio', 'Fernandez Hurtado', 23, '26836597P', new Date(2000, 6, 11), 'verde', 'mujer', [primeraResidenciaRocio, segundaResidenciaRocio], [mailRocio], [telefonoFijoRocio, telefonoMovilRocio], "Trabaja en la localidad de la segunda residencia");
var primeraResidenciaIsabel = new direccion_1.Direccion("Calle Malaga", 2, 3, "A", 29130, "Alhaurin de la Torre", "Malaga");
var segundaResidenciaIsabel = new direccion_1.Direccion("Avenida del Lido", 23, 1, "A", 29620, "Torremolinos", "Malaga");
var mailPersonalIsabel = new mail_1.Mail("personal", "isabelguerrero89@hotmail.com");
var mailTrabajoIsabel = new mail_1.Mail("personal", "isabel@guerreroconstrucciones.com");
var telefonoFijoIsabel = new telefono_1.Telefono("fijo", 951786538);
var telefonoMovilIsabelPersonal = new telefono_1.Telefono("movil", 667573295);
var telefonoMovilIsabelTrabajo = new telefono_1.Telefono("movil", 657342513);
var datosIsabel = new persona_1.Persona('Isabel', 'Guerrero Gonzalez', 33, '26745689T', new Date(1989, 9, 20), 'negro', 'Mujer', [primeraResidenciaIsabel, segundaResidenciaIsabel], [mailPersonalIsabel, mailTrabajoIsabel], [telefonoFijoIsabel, telefonoMovilIsabelPersonal, telefonoMovilIsabelTrabajo], "Tiene la segunda residencia alquilada todo el año");
var primeraResidenciaIsmael = new direccion_1.Direccion("Calle San Matias", 19, 9, "C", 18009, "Granada", "Granada");
var segundaResidenciaIsmael = new direccion_1.Direccion("Calle Bergantin San Jose", 8, 1, "A", 18613, "Motril", "Granada");
var mailPersonalIsmael = new mail_1.Mail("personal", "ismaelpareja@gmail.com");
var mailTrabajoIsmael = new mail_1.Mail("trabajo", "ime04@parejabogados.es");
var telefonoFijoIsmael = new telefono_1.Telefono("fijo", 958456218);
var telefonoMovilIsmael = new telefono_1.Telefono("movil", 608465728);
var datosIsmael = new persona_1.Persona('Ismael', 'Pareja Gutierrez', 43, '44590853P', new Date(1979, 10, 9), 'azul', 'hombre', [primeraResidenciaIsmael, segundaResidenciaIsmael], [mailPersonalIsmael, mailTrabajoIsmael], [telefonoFijoIsmael, telefonoMovilIsmael], "La segunda residencia es de alquiler");
console.log("Contactos antes del cambio:");
console.log(datosRocio);
console.log(datosIsabel);
console.log(datosIsmael);
var agenda = new Array(datosRocio, datosIsabel, datosIsmael);
var dniABuscar = "26745689T";
var personaAEditar = agenda.find(function (persona) { return persona.dni === dniABuscar; });
var nuevaDireccion = new direccion_1.Direccion("Calle Fernando el Catolico", 35, 1, false, 29012, "Malaga", "Malaga");
var nuevoMail = new mail_1.Mail("trabajo", "alquilervacacional@ayuntamientodemalaga.org");
var nuevoTelefono = new telefono_1.Telefono("fijo", 952396540);
personaAEditar.agregarNuevaDireccion(nuevaDireccion);
personaAEditar.agregarNuevoMail(nuevoMail);
personaAEditar.agregarNuevoTelefono(nuevoTelefono);
console.log("Contactos después del cambio:");
console.log(datosRocio);
console.log(datosIsabel);
console.log(datosIsmael);
